name: Continous Integration
on: [push]

jobs:
  build:
    run-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: make lint
    - name: Test
      run: make test

